name: Haskell CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: cabal2json
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: make
    - uses: actions/upload-artifact@v2
      with:
        name: build-${{ runner.os }}
        path: cabal2json.min.js
