name: Haskell CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://hydra.iohk.io https://cache.nixos.org/
    - uses: cachix/cachix-action@v12
      with:
        name: cabal2json
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: make
    - uses: actions/upload-artifact@v3
      with:
        name: build-${{ runner.os }}
        path: cabal2json.wasm
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: cabal2json.wasm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
