name: Haskell CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: make
    - uses: actions/upload-artifact@v2
      with:
        name: build-${{ runner.os }}
        path: cabal2json.min.js
